# Build dock image:
#    docker build -t flask-ubuntu:latest -f Dockerfile-ubuntu .
#
# In flask app directory, run dock container:
#    docker run -it --rm -p 5000:5000 -v "$PWD":/app flask-ubuntu:latest

FROM ubuntu:groovy

MAINTAINER Fan Hongtao <fanhongtao@gmail.com>

RUN set -eux \
# Switch mirrors for Ubuntu
    && cp /etc/apt/sources.list /etc/apt/sources.list.bak \
    && sed -i 's/security.ubuntu/mirrors.aliyun/g' /etc/apt/sources.list \
    && sed -i 's/archive.ubuntu/mirrors.aliyun/g' /etc/apt/sources.list

# Install
RUN apt update \
    && apt install -y python3 python3-pip \
    && pip3 install flask -i https://mirrors.aliyun.com/pypi/simple/

WORKDIR /app
EXPOSE 5000
CMD ["python3", "app.py"]
